### ISSUE TITLE
We need a formal review process

### ISSUE THREAD

**Issue by vermiculus** [VoLuong/Begin-Latex-in-minutes#21]
If this repository is going to be a thing, we should impose some sort of review process to vet incoming information.

A large problem the LaTeX community has been facing has been the rampant misinformation spread by outdated oral tradition and simple misunderstandings. (Such discussions are available in the TeX.SX chat archives, the meta site, and of course LaTeX-L.) At present, this repository is not helping the situation, but I can hold out hope that it could become a very valuable resource with a bit of work and a lot of discipline.

I propose that all incoming pull requests be reviewed for technical accuracy and current best practice (as far as a repository like this can hope to manage; 'best practice' often relies on the specific application). Hopefully this can curb issues like #18 cropping up again. Such reviews should be completed before a pull request is accepted.

**Comment by vermiculus** [comment]
I've given an example of what such review could look like in #20.

**Comment by luong-komorebi** [comment]
@vermiculus 

> If this repository is going to be a thing, we should impose some sort of review process to vet incoming information. [....] I propose that all incoming pull requests be reviewed for technical accuracy and current best practice

Yes, I do agree.  
When I merged #18 , I did look carefully into the site and also have the same opinion that : It's not a LaTeX Editor ,but it has the capability of rendering LaTeX math experessions thanks to MathJax. Moreover, the author of that PR didn't explicitly say that it was an LaTeX but markdown editor, so I thought it was fine merging such things in the #addtional-tools part.

**Comment by luong-komorebi** [comment]
@vermiculus  

> A large problem the LaTeX community has been facing has been the rampant misinformation spread by outdated oral tradition and simple misunderstandings. (Such discussions are available in the TeX.SX chat archives, the meta site, and of course LaTeX-L.) At present, this repository is not helping the situation, but I can hold out hope that it could become a very valuable resource with a bit of work and a lot of discipline.  

To be honest, I am not a LaTeX guru, but a student who is interested in sharing some good things about LaTeX while learning it for a project. I do hope that someone will come across this ( I didn't expect it to be thousands of people because I intially wrote this for my classmates only ) and find it helpful as well as motivating, not daunting like the way people feel towards LaTeX. Thus,  I am sorry if this repo doesnt help solving big problems or I am sorry that my little experience in LaTeX hadn't come accross such problems. Plus I am not experienced enough to decide whether something is current best practice or not.  Please forgive me if I made foolish beginner's mistake.     

Nevertheless, I do hope to contribute some resources to the community out there. If you want to help, it's welcomed and we will discuss more in the future.

**Comment by luong-komorebi** [comment]
P/S : sorry for the late reply. I got a rough day at school.
