### ISSUE TITLE
Translating of "Hello, I love you all." is wrong

### ISSUE THREAD

**Issue by xreiju** [VoLuong/Begin-Latex-in-minutes#28]
こんにちは、私はあなたのすべてを愛しています。
Hello, I love you all.

---

If you mean "you all" is like "you guys", you should translate to "こんにちは、私はあなた達みんなを愛しています。".
"あなたのすべて" refers to "everything you have", so you should use "あなた達みんな" as "you all".

**Comment by luong-komorebi** [comment]
Hi @sakurapleasure , 
First of all, I would like to say that all my translation is done via Google Translate ( *because I don't speak Japanese* )
![image](https://cloud.githubusercontent.com/assets/15828926/21010919/44af90c2-bd81-11e6-8d97-fbd4c6495382.png)

![image](https://cloud.githubusercontent.com/assets/15828926/21010903/344ad0ac-bd81-11e6-9a9f-03296626350e.png)

Yes I do mean **I love you guys** or more specifically, I meant to say **I love all of you who are reading this** , but in English, it is not so critical that you have to point out who is **all** so I choose to say **I love you all** for general meaning. 
I didn't know it would cause some error in Japanese since the sentence seems to be very basic. 
Thank you for your issue. But once again, can you recheck if this sentence is seriously wrong or it's just vague in meaning ?  Is it worth fixing it ?

**Comment by xreiju** [comment]
>Is it worth fixing it?

Yes. if you mean **I love you all** as **I love all of you who are reading this**, The sentence translated to Japanese is totally wrong.
"あなたのすべてを愛しています" can be meant like "(I have a girlfriend/boyfriend, and) I love her/him and all of things about her/him." It can be also meant "I love you and all things you have" as other example.

It seems my sentence is translated to "Hello, I love you guys". Probably you think "you guys" doesn't fit to this article, but in Japanese, "あなた達みんな" is not offensive so it's correct.

**Comment by luong-komorebi** [comment]
@sakurapleasure  thank you, I understood now. 
If possible, can you recommend me a better, more grammatically correct and concise sentence than "Hello, I love you all" ? I would like a recommendation from a native speaker for the example.

**Comment by xreiju** [comment]
"Thank you for reading this article" in Japanese:
+ "この記事を読んでくれてありがとう。"
+ "この記事を読んでいただきありがとうございます。"

The last one is more stiff. I recommend this sentence. The first one is more concise.
As a reader of this article, I think "Thank you for reading this article" is better than "Hello, I love you guys". Actually You may use either both.

**Comment by luong-komorebi** [comment]
@sakurapleasure  a1afd14267b4e428bddc0fbec926c218e7cd5e10 thank you so much.
