### ISSUE TITLE
TeXstudio is a nicer editor

### ISSUE THREAD

**Issue by Kwpolska** [VoLuong/Begin-Latex-in-minutes#8]
TeXstudio is a fork of TeXmaker with more features. Perhaps you should promote that instead?

**Comment by luong-komorebi** [comment]
@Kwpolska  I actually didn't want to promote anything. :sob: I was scared that people think I was doing promotion or that I treated some products unfair not to mention their names here. What I "highly suggest" to people are just what I have had the chance to use and I thought it would be nice to save time finding tools for beginners. :sob:  I will consider make a section for "tools" so that all tools are listed equally. Thank you

**Comment by luong-komorebi** [comment]
@Kwpolska  Can you do a pull request adding LaTeX compilers / editors that you favor in the Additional Tools section?
